### ISSUE TITLE
text area content replace as a paragraph not line by line

### ISSUE THREAD

**Issue by ERajkumar** [silverslice/docx-template#3]
I am working in contract  based on documents,  I have some text area values, I will replace  this textarea values to doc variable, but its replaced,  but its print like a paragraph, I need line by line. Suggest me How to fix this.

Reference:

![text_area_alignment](https://user-images.githubusercontent.com/11554190/36669565-50ba1bd2-1b1b-11e8-8294-7c230ada43a1.png)

**Comment by silverslice** [comment]
@ERajkumar Hello! I've added multiline replacement. Run `composer update silverslice/docx-template` and try to use `replaceMultiline` method.

**Comment by felixprawira** [comment]
can it replace image too? like {%image} get replace with actual image

**Comment by silverslice** [comment]
@felixprawira no, only text replacement is available. Try to see https://github.com/PHPOffice/PHPWord/issues/550 for solution.
